apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.application.name.prefix }}-secret
  namespace: {{ .Values.environment }}
data:
  {{- range $key, $val := .Values.env.secrets }}
  {{ $key }}: {{ $val }}
  {{- end }}
