apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.application.name.prefix }}-configmap
  namespace: {{ .Values.environment }}
data:
  {{- range $key, $val := .Values.env.configmaps }}
  {{ $key }}: "{{ $val }}"
  {{- end}}
