apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.application.name.prefix }}-deployment
  namespace: {{ .Values.environment }}
  labels:
    app: {{ .Values.application.name.prefix }}
    environment: {{ .Values.environment }}
    app.kubernetes.io/name: {{ .Values.application.name.prefix }}
    app.kubernetes.io/instance: {{ .Values.application.name.prefix }}-instance
    app.kubernetes.io/version: {{ .Values.image.tag }}
    app.kubernetes.io/component: microservice
    app.kubernetes.io/part-of: financial-management-system
    app.kubernetes.io/managed-by: financial-management-system
spec:
  selector:
    matchLabels:
      app: {{ .Values.application.name.prefix }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.application.name.prefix }}
    spec:
      automountServiceAccountToken: false
      containers:
        - name: {{ .Values.application.name.prefix }}-container
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.application.targetPort }}
          resources:
            requests:
              cpu: 150m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 128Mi
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 2000
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
              - all
          env:
          {{- include "helpers.list-env-configmaps" . | indent 12 }}
          {{- include "helpers.list-env-secrets" . | indent 12 }}
          livenessProbe:
            httpGet:
              path: /health-check/live
              port: {{ .Values.application.targetPort }}
            failureThreshold: 5
            initialDelaySeconds: 30
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health-check/ready
              port: {{ .Values.application.targetPort }}
            failureThreshold: 5
            initialDelaySeconds: 30
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 5
          startupProbe:
            httpGet:
              path: /health-check/live
              port: {{ .Values.application.targetPort }}
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
