---
# Source: balances-api-chart/templates/hpa.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bal-api-hpa
  namespace: development
  labels:
    app: bal-api
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: bal-api-deployment
    minReplicas: 1
    maxReplicas: 3
    metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
