---
# Source: balances-api-chart/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: bal-api-secret
  namespace: development
data:
  MONGODB_DATABASE: YmFsYW5jZXMtbW9uZ29kYg==
  MONGODB_URL: bW9uZ29kYitzcnY6Ly9jb250YWluZXI6Y29udGFpbmVyQGxvY2FsaG9zdDoyNzAxOS9iYWxhbmNlcy1tb25nb2Ri